### ISSUE TITLE
Admob binding - Banner not working

### ISSUE THREAD

**Issue by mcolombo** [BlueRiverInteractive/robovm-ios-bindings#100]
Hi all,

Did someone successfully made the GADBannerView work using these bindings?
Interstitials work great, but the banner throws an error.
Im using the .a library located in " libproj / admob / admob / libgoogleadmobads.a"
If i use the one inside "libs/libadmob.a", nothing works (not even insterstitials).

Im getting: org.robovm.objc.ObjCClassNotFoundException: GADAdSizeWrapped
I tried using the latest .a library downloaded from google for iOS. 
I posted another issue related to this, but updating the .a file did not work.

Is there a way to make the banners work?
Thanks a lot.

**Comment by BlueRiverInteractive** [comment]
AdMob is now officially supported as a RoboPod: https://github.com/robovm/robovm-robopods

Just add the following to your Gradle:
```
dependencies {
   ... other dependencies ...
   compile "org.robovm:robopods-google-mobile-ads-ios:1.5.0"
}
```
or maven files:
```
<dependency>
   <groupId>org.robovm</groupId>
   <artifactId>robopods-google-mobile-ads-ios</artifactId>
   <version>1.5.0</version>
</dependency>
```

Please use the RoboPod from now and post any issues you encounter on their issues list. Thanks!
