### ISSUE TITLE
Issue with Admob bindings

### ISSUE THREAD

**Issue by barodapride** [BlueRiverInteractive/robovm-ios-bindings#125]
Hello,

I was trying to implement Admob bindings by following the sample but I was having an issue that was causing my screen not to respond to any touch inputs. I narrowed down the issue to this line:

window.makeKeyAndVisible();

I was able to work around this issue by calling this method in my interstitial's didReceiveAd delegate method and then calling window.setHidden(true); in my interstitial's didDismissScreen method.

I looked at the issues listed here and did not see anything like it. Am I doing something wrong? I did a little research about these methods in the iOS world but I don't understand enough about what is happening to figure it out. Should the Admob sample be changed or did I do something wrong on my end?

**Comment by BlueRiverInteractive** [comment]
AdMob is now officially supported as a RoboPod: https://github.com/robovm/robovm-robopods

Just add the following to your Gradle:
```
dependencies {
   ... other dependencies ...
   compile "org.robovm:robopods-google-mobile-ads-ios:1.5.0"
}
```
or maven files:
```
<dependency>
   <groupId>org.robovm</groupId>
   <artifactId>robopods-google-mobile-ads-ios</artifactId>
   <version>1.5.0</version>
</dependency>
```

Please use the RoboPod from now and post any issues you encounter on their issues list. Thanks!
