### ISSUE TITLE
How to fix NoSuchMethodError: org.robovm.apple.storekit.SKProductsRequest after update?

### ISSUE THREAD

**Issue by AgrarPirat** [BlueRiverInteractive/robovm-ios-bindings#133]
Hello,

I just did an update of the whole build environment including libGDX, roboVM, the bindings, eclipse, plugins and graddle. Now all of a sudden the in App purchase crashes with the following messages:
```
[InAppPurchaseManager] Requesting product data...
java.lang.NoSuchMethodError: org.robovm.apple.storekit.SKProductsRequest.<init>(Lorg/robovm/apple/foundation/NSSet;)V
	at org.robovm.bindings.inapppurchase.InAppPurchaseManager.requestProducts(InAppPurchaseManager.java)
	at org.robovm.bindings.inapppurchase.InAppPurchaseManager.requestProducts(InAppPurchaseManager.java)
```
Do you have any ideas what could be the cause of this problem or how to fix it?
Any advice is welcome.
Thank you!

**Comment by BlueRiverInteractive** [comment]
Did you manage to fix this problem?

**Comment by BlueRiverInteractive** [comment]
The in-app-purchase bindings have been updated and that issue should be gone.
