### ISSUE TITLE
No new snapshots since Dec, 12, 2014

### ISSUE THREAD

**Issue by alexander-mironov** [BlueRiverInteractive/robovm-ios-bindings#144]
No new snapshots here: [http://libgdx.badlogicgames.com/robovm-ios-bindings/](http://libgdx.badlogicgames.com/robovm-ios-bindings/)

**Comment by BlueRiverInteractive** [comment]
This repository is deprecated and will be replaced by https://github.com/robovm/robovm-robopods.
The snapshots will be deleted in the future.
