### ISSUE TITLE
ExceptionInInitializerError when using Google analytics

### ISSUE THREAD

**Issue by bradfail** [BlueRiverInteractive/robovm-ios-bindings#145]
updated app to robovm 1.0.0-beta-03 and gdx 1.5.3

when making any call to GAI java.lang.ExceptionInInitializerError is thrown

issue did not occur when using 1.0.0-beta-01

**Comment by bradfail** [comment]
error caused by misplaced libgoogleanalytics.a

**Comment by voidstarfire** [comment]
So where does one place the file?

**Comment by bradfail** [comment]
it is in the libs folder but i had accidentally deleted it
