### ISSUE TITLE
AdMob Banner won't show on iPhone simulator or real device in landscape mode

### ISSUE THREAD

**Issue by mcolombo** [BlueRiverInteractive/robovm-ios-bindings#146]
Hi,
I've been fighting this for a lot of days now! It is really weird.
I configured admob using smartBannerLandscape, and works perfectly in iPad.
However, when trying it on an iPhone simulator or real iPhone device (tested on iPhone 5s, simulator and device), the ad won't show. It does load the request since the adapter hits the "didReceiveAd" method.
If i force the simulator in portrait mode through the info.plist.xml file, the ad DOES show.

I also tried any other type of banner, but none will show in landscape mode for iPhone.
Am i missing something here?
Thanks in advance!

This is my ad configuration (i already tried many many variations here with no success, even the libgdx's offcial one):
```javascript
UIViewController controller = iOSApplication.getUIViewController();
		UIWindow window = new UIWindow(UIScreen.getMainScreen().getBounds());
		mGADBannerView = new GADBannerView(GADAdSize.smartBannerLandscape());
		mGADBannerView.setRootViewController(controller);
		mGADBannerView.setAdUnitID(ADMOB_BANNER_ID);
		mGADBannerView.setFrame(new CGRect(0, window.getBounds().getSize()
				.getHeight()
				- mGADBannerView.getFrame().getSize().getHeight(),
				mGADBannerView.getFrame().getSize().getWidth(), mGADBannerView
						.getFrame().getSize().getHeight()));
		GADRequest req = new GADRequest();
		mGADBannerView.loadRequest(req);
		mGADBannerView.setDelegate(new GADBannerViewDelegateAdapter());
		controller.getView().addSubview(mGADBannerView);
		Foundation.log("[info] " + LogUtil.TAG + ": "
				+ "Ad created!!");
```

**Comment by mcolombo** [comment]
Update: the problem seems to happen on iOS 7.1.
Tried it on iPhone 4, 5s, 6, 6 plus simulators with iOS 8.1 and worked perfectly.

**Comment by dzungpv** [comment]
You can use this code, it copy from one of my game has been publish to appstore.
``
		// We need a view controller to see ads.
		bannerViewController = new UIViewController();
                viewadd = bannerViewController.getView();

		// Create a admob banner.
		GADBannerView banner = new GADBannerView(GADAdSize.smartBannerLandscape());
		banner.setAdUnitID(admob_id);
		banner.setDelegate(new GADBannerViewDelegateAdapter() {
			@Override
			public void didReceiveAd(GADBannerView view) {
				super.didReceiveAd(view);
				Gdx.app.debug("didReceiveAd banner", "");
			}

			@Override
			public void didFailToReceiveAd(GADBannerView view,
					GADRequestError error) {
				super.didFailToReceiveAd(view, error);
				Gdx.app.debug("didFailToReceiveAd banner:", error.toString());
			}
		});

		banner.setRootViewController(gdxApplication.getUIViewController());
		viewadd.addSubview(banner);
		banner.setFrame(new CGRect(
				(screenWidth - banner.getFrame().getWidth()) / 2, 0, banner
						.getFrame().getWidth(), banner.getFrame().getHeight()));
		// banner.setBackgroundColor(new UIColor(1, 0, 0, 1)); // Remove this
		// after testing.
		banner.loadRequest(request);
		gdxApplication.getUIViewController().getView().addSubview(viewadd); 
``

**Comment by mcolombo** [comment]
Thanks dzungpv.
Just tried this (and many other variations) but the banner still does not show on iOS 7.1 in landscape mode.
Does it work for you in landscape with iOS 7.1?

**Comment by dzungpv** [comment]
Add this code for ios 7.1
	double screenWidth = UIScreen.getMainScreen().getApplicationFrame()
				.size().height();
		if(majorOsVersion>7){
			screenWidth = UIScreen.getMainScreen().getApplicationFrame()
					.size().width();
		}

**Comment by mcolombo** [comment]
It Worked!!
Not sure why i should use inverted width for ios7, but worked!

Thanks a lot dzungpv!



Mariano  Colombo

Blyts - www.blyts.com
Buenos Aires, Argentina.

**Comment by mohdajim** [comment]
hi. i am trying to integrate admob in my libgdx game. from last 2 weeks but nothing works help me on this thanks in advance pls help help

**Comment by mohdajim** [comment]
is i need to create separate class for ad showing or withing ioslauncher class.. pls help me on this

**Comment by BlueRiverInteractive** [comment]
AdMob is now officially supported as a RoboPod: https://github.com/robovm/robovm-robopods

Just add the following to your Gradle:
```
dependencies {
   ... other dependencies ...
   compile "org.robovm:robopods-google-mobile-ads-ios:1.5.0"
}
```
or maven files:
```
<dependency>
   <groupId>org.robovm</groupId>
   <artifactId>robopods-google-mobile-ads-ios</artifactId>
   <version>1.5.0</version>
</dependency>
```

Please use the RoboPod from now and post any issues you encounter on their issues list. Thanks!
