### ISSUE TITLE
Admob banner crash on IPAD when build with 64 bit

### ISSUE THREAD

**Issue by dzungpv** [BlueRiverInteractive/robovm-ios-bindings#152]
I found this problem and it prevent me to submit 64 ipa to Apple. Only crash with Ipad 64 bit, tested both on simulator and real device (Ipad mini retina 8.1.2 - 8.1.3).

Full crash log.
https://gist.github.com/dzungpv/4770bfcf4c1e371e8c86

**Comment by dzungpv** [comment]
After add x86_64 to architectures (xcode project) i can debug on simulator. Note that this tag missing from some lib here so can not debug with 64 bit simulator.

But it still not run on real device. Anyone have admob banner work on Ipad 64 bit build?

I try GADBannerView banner = new GADBannerView(GADAdSize.banner());

GADBannerView banner = new GADBannerView(GADAdSize.smartBannerPortrait());

**Comment by FrankNT** [comment]
This topic might help you finger out was is happening
https://groups.google.com/forum/#!msg/robovm/ohkwSrecUoc/Ut-RzazFPIcJ

**Comment by BlueRiverInteractive** [comment]
Should be fixed in robovm-beta-04

**Comment by dzungpv** [comment]
It still here, i try with beta 4 and latest nightly.

**Comment by FrankNT** [comment]
I'm OK now. Problem solved.
