### ISSUE TITLE
Chartboost's Rewarded Video not present

### ISSUE THREAD

**Issue by ASMCOM** [BlueRiverInteractive/robovm-ios-bindings#159]
Is it possible to update the bindings to include the method cacheRewardedVideoand to support rewarded video ?

**Comment by teestudio** [comment]
It's already fixed, we use a new version of binding successfully.

**Comment by BlueRiverInteractive** [comment]
The Chartboost binding is subject to be deleted. Please use the new iOS RoboPod for Chartboost: https://github.com/robovm/robovm-robopods
