### ISSUE TITLE
Chartboost ChartboostDelegateAdapter() not working.

### ISSUE THREAD

**Issue by ASMCOM** [BlueRiverInteractive/robovm-ios-bindings#160]
I'm using the following code in order to track Chartboost's ads but unfortunately it's not working any more.

I'm using:
chartboost-1.0.0-SNAPSHOT
gdxVersion = '1.5.3'
roboVMVersion = '1.0.0-SNAPSHOT'

ChartboostDelegate delegate = new ChartboostDelegateAdapter() {
            @Override
            public void didCacheInterstitial(String location) {
                super.didCacheInterstitial(location);
                System.out.println("Cacheing ads for: " + location);
            }
            @Override
            public void didDisplayInterstitial(String location) {
                super.didDisplayInterstitial(location);
                System.out.println("Ads displayed: " + location);
            }
            @Override
            public void didCloseInterstitial(String location) {
                super.didCloseInterstitial(location);
                System.out.println("Closeing ads for: " + location);
        };
        Chartboost.start(VersionHandler.iOS_CHARTBOOST_APP_ID
                VersionHandler.iOS_CHARTBOOST_APP_SIGNATURE, delegate);
        Chartboost.cacheInterstitial("MY_AD");

**Comment by obigu** [comment]
Have a look to this post:
https://groups.google.com/forum/#!searchin/robovm/chartboost/robovm/ot84hWAjBZM/DS9J9bXSvmIJ
and then to this other post because you may face some performance problems once you solve the delegate not being called: 
https://groups.google.com/forum/#!topic/robovm/W0QcuZN7H1E

**Comment by BlueRiverInteractive** [comment]
The Chartboost binding is subject to be deleted. Please use the new iOS RoboPod for Chartboost: https://github.com/robovm/robovm-robopods
