### ISSUE TITLE
Getting rid of Admob Xcode project

### ISSUE THREAD

**Issue by obigu** [BlueRiverInteractive/robovm-ios-bindings#161]
Hi, this should probably be labeled as an enhancement.

I have been investigating how to get rid of the Admob bindings Xcode project because it's a real pain and it's causing lots of issues. Correct me if I'm wrong but it looks as if it was created to be able to make wrappers over the Global symbols from GADAdSize and GADRequestError because they are hidden.

If the wrapper project is not used, when trying to directly export these symbols warning such as this appear
```
 (03/03/15 17:21:50: [ WARN] ld: warning: cannot export hidden symbol _kGADAdSizeBanner from /Users/xxxx/git/ovi/ios/libs/libadmob.a(GADAdSize.o))
```

The following issue opened more than a year ago https://github.com/robovm/robovm/issues/264 seems to imply that we need the wrapper to make these hidden symbols "visible".

I've created custom bindings not to need the wrapper project (in a similar way as Chartboost does) but I have been unsuccessful so far as when I refer to a specific GADAdSize the following Runtime error occurs (that most probably happen because the warnings before):
```
Unable to set adSize property with GADAdSize: {0, 0}, 0. Please use one of the standard ad sizes or create a custom ad size using GADAdSizeFromCGSize.
java.lang.RuntimeException: Objective-C initialization method returned nil
```

Do we need to wait until https://github.com/robovm/robovm/issues/264 is solved or there's a workaround?

**Comment by BlueRiverInteractive** [comment]
AdMob is now officially supported as a RoboPod: https://github.com/robovm/robovm-robopods

Just add the following to your Gradle:
```
dependencies {
   ... other dependencies ...
   compile "org.robovm:robopods-google-mobile-ads-ios:1.5.0"
}
```
or maven files:
```
<dependency>
   <groupId>org.robovm</groupId>
   <artifactId>robopods-google-mobile-ads-ios</artifactId>
   <version>1.5.0</version>
</dependency>
```

Please use the RoboPod from now and post any issues you encounter on their issues list. Thanks!
