### ISSUE TITLE
facebook binding - invitable_friend request issue

### ISSUE THREAD

**Issue by fuatcoskun** [BlueRiverInteractive/robovm-ios-bindings#162]
I am getting "The operation couldn’t be completed. (com.facebook.sdk error 5.)" error when trying to get invitable friends via Facebook request. I have created following post on stackoverflow.

http://stackoverflow.com/questions/28881948/robovm-facebook-binding-invitable-friends-issue-com-facebook-sdk-error-5

I really appreciate if you can check it.

**Comment by jsras** [comment]
Have you remembered to add a canvas to your Facebook app? This is required in order to use invitable friends and get your Facebook app recognized as a game. 

I've had the exact same error as you because of this.

**Comment by BlueRiverInteractive** [comment]
The latest Facebook bindings have been released as RoboPod: https://github.com/robovm/robovm-robopods/tree/master/facebook

The only thing you need to do is to add a maven or gradle dependency to your project, like
> compile "org.robovm:robopods-facebook-ios:1.0-SNAPSHOT"
