### ISSUE TITLE
AdMob Errors no long appear to be coming through didFailToReceiveAd - 1.0.0

### ISSUE THREAD

**Issue by MonsterOfCookie** [BlueRiverInteractive/robovm-ios-bindings#165]
Hey,

When using the admob binding - with out a network connection, I would receive the following message when I went to load an ad - via the didFailToReceiveAd method call.

```
WARN: Failed to call getClassDomain() for the NSError subclass org.robovm.bindings.admob.GADRequestError
Error Domain=com.google.ads 
Code=2 
"Request Error: A network error occurred." 
UserInfo=0x16de4730 {NSLocalizedDescription=Request Error: A network error occurred., NSLocalizedFailureReason=Request Error: A network error occurred.}	
```

Which is fine, I purposefully don't have a connection. 

However I have recently updated to 1.0.0 of the binding and I no long receive the error message part.

**Comment by BlueRiverInteractive** [comment]
AdMob is now officially supported as a RoboPod: https://github.com/robovm/robovm-robopods

Just add the following to your Gradle:
```
dependencies {
   ... other dependencies ...
   compile "org.robovm:robopods-google-mobile-ads-ios:1.5.0"
}
```
or maven files:
```
<dependency>
   <groupId>org.robovm</groupId>
   <artifactId>robopods-google-mobile-ads-ios</artifactId>
   <version>1.5.0</version>
</dependency>
```

Please use the RoboPod from now and post any issues you encounter on their issues list. Thanks!
