### ISSUE TITLE
Is there already sb working on Facebook SDK 4.0.0 bindings?

### ISSUE THREAD

**Issue by TomGrill** [BlueRiverInteractive/robovm-ios-bindings#169]
Is there already sb working on Facebook SDK 4.0.0 bindings? I am not capable doing this by myself but I would try to find sb do this work if it is not planed by contributors to this rep in the near future.

**Comment by mickmuzac** [comment]
For that matter, does anyone know how to create a FacebookDialog for Open Graph requests?

How should the action and object be constructed?

**Comment by voidstarfire** [comment]
I'd +1 this.

**Comment by BlueRiverInteractive** [comment]
The latest Facebook bindings have been released as RoboPod: https://github.com/robovm/robovm-robopods/tree/master/facebook

The only thing you need to do is to add a maven or gradle dependency to your project, like
> compile "org.robovm:robopods-facebook-ios:1.0-SNAPSHOT"
