### ISSUE TITLE
RoboVM 1.2.0

### ISSUE THREAD

**Issue by voidstarfire** [BlueRiverInteractive/robovm-ios-bindings#174]
Google Analytics library is broken in RoboVM 1.2.0

libgoogleanalytics.a 
16:03:20.799 [DEBUG] [org.gradle.api.Task]     -force_load /Users/appsure/Documents/Apps/app/ios/build/libs/ios/libObjectAL.a -framework MobileCoreServices
16:03:23.128 [ERROR] [org.gradle.api.Task] Undefined symbols for architecture armv7:
16:03:23.128 [ERROR] [org.gradle.api.Task]   "_inflate", referenced from:
16:03:23.131 [ERROR] [org.gradle.api.Task]       +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libgoogleanalytics.a(GAICompressionUtil.o)
16:03:23.303 [ERROR] [org.gradle.api.Task]      (maybe you meant: _str_inflater_20_3D_3D_20null_00_ptr, _str_inflater_20_3D_3D_20null_00 , _[j]str_inflater_20_3D_3D_20null_00[ldcstring] , _str_inflateImpl_00 , _Java_java_util_zip_Inflater_inflateImpl___3BIIJ , _str_inflate_00 , _Java_java_util_zip_Inflater_inflateImpl )
16:03:23.304 [ERROR] [org.gradle.api.Task]   "_deflate", referenced from:
16:03:23.306 [ERROR] [org.gradle.api.Task]       +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] i

**Comment by WillCalderwood** [comment]
I'm having the same issue. Have you made any progress on this?

**Comment by voidstarfire** [comment]
Unfortunately not, having this issue with a few bindings. Maybe they forgot an essencial lib?

**Comment by rotter** [comment]
I was having problem when trying to run any iOS project after upgrading RoboVM 1.2.0 but I postponed debugging it until I was ready to submit an update to the App Store. Maybe this was the culprit? If so this worries me a lot, as I cant update any app without Analytics, so maybe we have to downgrade to RoboVM 1.1?

Best

> On May 13, 2015, at 10:52, voidstarfire <notifications@github.com> wrote:
> 
> Unfortunately not, having this issue with a few bindings. Maybe they forgot an essencial lib?
> 
> —
> 
> 

Original issue:

“
Google Analytics library is broken in RoboVM 1.2.0
libgoogleanalytics.a 
16:03:20.799 [DEBUG] [org.gradle.api.Task] -force_load /Users/appsure/Documents/Apps/app/ios/build/libs/ios/libObjectAL.a -framework MobileCoreServices

"

**Comment by voidstarfire** [comment]
It's a real shame no one is keeping the bindings updated, it's going to kill RoboVM.

**Comment by WillCalderwood** [comment]
I fixed all the breaking changes in LibGDX 1.6.0 which would appear to not work with RoboVM 1.1.0 so it doesn't look like I can roll back.

**Comment by voidstarfire** [comment]
Are you saying the bindings now work with 1.2.0?

**Comment by obigu** [comment]
I'm not using Google Analytics in my projects but what you're describing may be a libGDX Gradle configuration problem as currently libGDX will automatically delete any 3rd party .a library from the robovm.xml descriptor when building the project via Gradle.

Have a look at https://github.com/libgdx/libgdx/issues/3027 and try the workaround see if that fixes your issue.

**Comment by voidstarfire** [comment]
Yes I got around that by doing this in iOS gradle:

//For analytics //Can be done with for loop *.a
task copyStaticLib(type: Copy) {
    from 'libs/libgoogleanalytics.a'
    into 'build/libs/ios/'
}

**Comment by obigu** [comment]
Check out this:

https://github.com/libgdx/libgdx/issues/3063

**Comment by voidstarfire** [comment]
Still doesn't resolve the issue with static libraries not working in version 1.2.0

**Comment by obigu** [comment]
I'm using 2 static libraries with RoboVM 1.2.0 with no issues. Have you tried the workaround on the referred JIRA?

**Comment by voidstarfire** [comment]
Did you try BlueRiver analytics? It's not a problem with the library being overridden it's a problem with RoboVM (me thinks) or the library being out of date hmm.

**Comment by rotter** [comment]
I have almost not tried/used 1.2.0 yet, but I’ve had an issue in the past with the bindings being outdated, so I had to update the RoboVM version on the build.gradle of the bindings (outside Eclipse, on the root folder of the bindings) and then Gradle-Refresh All on the project of the bindings so it started using the correct versions of the dependencies.

On that occasion there was no crash/problem due to this issue, but when building the final .IPA it would add 2 versions of the same libraries (the one referenced by the lib, and the one referenced by my game).

Best

**Comment by obigu** [comment]
I'm not using Google Analytics. I use BlueRiver's binding classes but I always download the native libraries from the original sources. Sorry not to be able to help you.

**Comment by voidstarfire** [comment]
Ah the Google Analytics library for BlueRiver is out of date. The new one even has a different name. Thanks Rotter, not sure what you mean. I've updated all that needs to be updated, ./gradlew clean and deleted the RoboVM cache. Seems it's on 1.2.0; just fails; Are you using Google Analytics?

**Comment by WillCalderwood** [comment]
See this thread:
http://www.badlogicgames.com/forum/viewtopic.php?t=19318&p=81107
axl had recompiled the analytics jar with the missing lib. I've just tried it and it fixes the problem.

**Comment by voidstarfire** [comment]
I can confirm that it now compiles but now I have the following error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GAITrackerImpl send:]: unrecognized selector sent to instance 0x1897ba20'

**Comment by BlueRiverInteractive** [comment]
Please add <lib>z</lib> to your robovm.xml libs node for the time being.

Google Analytics is subject to be released as RoboPod shortly. Please check the https://github.com/robovm/robovm-robopods issue tracker for more.

BTW essentially all of the bindings here will be deprecated soon and removed in favor of the updated RoboPods. Facebook has already been released as a robopod.
