### ISSUE TITLE
Google Play Games Services: No callback on registered GPGStatusDelegate instance

### ISSUE THREAD

**Issue by kutoman** [BlueRiverInteractive/robovm-ios-bindings#176]
Hello,
there is somehow no callback to my ```GPGStatusDelegate``` instance which I registered by 
```
this.gpgManager = GPGManager.sharedInstance();
gpgManager.setStatusDelegate(new ConnectionListener());
``` 
(Note: ConnectionListener extends NSObject implements GPGStatusDelegate).
When I call ```gpgManager.signInWithClientID(CLIENT_ID, false); ``` the accounts.google.com page shows up. And when I tap on 'Accept' the game screen gets reshown but my ```GPGStatusDelegate```instance does not receive anything.

**Comment by kutoman** [comment]
Finally, I could fix it. For those who are curious about. I just added the following lines to the class which extends ``IOSApplication.Delegate``

```
// copy-paste this to your app delegate.
    @Override
    public boolean openURL(UIApplication application, NSURL url, String sourceApplication, NSPropertyList annotation) {
        return GPPURLHandler.handleURL(url, sourceApplication, annotation);
    }
```

**Comment by julienvillegas** [comment]
This method has now been deprecated.
I have the same issue.
What would be the way to solve this issue now?
