### ISSUE TITLE
The admob version is too old,how can i update it?

### ISSUE THREAD

**Issue by yx421626416** [BlueRiverInteractive/robovm-ios-bindings#187]

**Comment by WillCalderwood** [comment]
https://github.com/robovm/robovm-robopods

**Comment by yx421626416** [comment]
thank you  for your answer but why is there no gradle file?

**Comment by WillCalderwood** [comment]
Read the usage section.

**Comment by yx421626416** [comment]
OK  thank you  very much.

**Comment by yx421626416** [comment]
can  you provide one sample for this issue?

**Comment by yx421626416** [comment]
I  try a lot  to change it what  I can use,but I  failed. Can you provide one example for me ?
