### ISSUE TITLE
Cannot get admob ads to work on iOS Simulator

### ISSUE THREAD

**Issue by mbazos** [BlueRiverInteractive/robovm-ios-bindings#38]
I cannot seem to get the admob ads to work on the simulator.  I keep getting:
<Google> To get test ads on this device, call: request.testDevices = @[ GAD_SIMULATOR_ID ];

Is this normal?  Unfortunately I don't have an iOS device handy to test this on a physical device.  Everything seems to load properly except I get that one <Google> error.  I am using the latest admob bindings from github & latest version of robovm.  Any help would be appreciated.

I have the following code running:

```
public void initializeAds() {
    if (!adsInitialized) {
        log.debug("Initalizing ads...");

        adsInitialized = true;
        adview = new GADBannerView(GADAdSizeManager.smartBannerPortrait());
        adview.setAdUnitID(Constants.ADMOB_KEY);
        adview.setRootViewController(iosApplication.getUIViewController());

        final GADRequest request = GADRequest.request();
        if (Constants.TEST_DEVICE_ENABLED) {
            final NSArray<?> testDevices = new NSArray<NSObject>(
                    new NSString(GADRequest.GAD_SIMULATOR_ID));
            request.setTestDevices(testDevices);
            log.debug("Test devices: " + request.getTestDevices());
        }

        adview.loadRequest(request);

        log.debug("Initalizing ads complete.");
    }
}
```

Here are the log outputs:
[debug] com.oporko.bff.IOSApplication: Initalizing ads...
[debug] com.oporko.bff.IOSApplication: Test devices: (
    Simulator
)
2014-04-09 20:00:56.484 IOSApplication[3460:70b] <Google> To get test ads on this device, call: request.testDevices = @[ GAD_SIMULATOR_ID ];
[debug] com.oporko.bff.IOSApplication: Initalizing ads complete.

**Comment by mohdajim** [comment]
hi.. i am trying your code but it showing me error on admob sdk something 6.12 and need to upgrade to latest 7.0 sdk what is the issue i am using same binding

**Comment by mohdajim** [comment]
i am almost trying this "Admob " integration from last 8-10 days atleast with your code i am able to see something related to admob now thank you so much . but not geeting ads

**Comment by mohdajim** [comment]
please tell me what to do?? plzzz
