### ISSUE TITLE
Upgrading Facebook Apps to Graph API v2.0+

### ISSUE THREAD

**Issue by mgrogin** [BlueRiverInteractive/robovm-ios-bindings#82]
I got this mail from facebook:

At our f8 event, we introduced Graph API v2.0 ( https://developers.facebook.com/blog/post/2014/04/30/f8/ ). API versions older than v2.0 expire on April 30, 2015. After this date, your apps will automatically be upgraded to v2.0.

Our data shows that it takes 80-140 days for 90% of people to update to the latest version of a mobile app. Because of this, we highly recommend you start building for Graph API v2.0+ today. This will help make sure that no one will experience any issues when using your app.

If you have any questions, please check out the FAQs. ( https://developers.facebook.com/docs/apps/faq)

Learn how to upgrade https://developers.facebook.com/docs/apps/upgrading

**Comment by mcolombo** [comment]
Hi!!
Im having issues updating to Facebook SDK 2.0.
I downloaded all the bindings as you said, but the warning still appears.

I couldn't find the ".a" files though to update the. Maybe that's the problem.
Where can i find those? 

Thanks in advance

**Comment by mcolombo** [comment]
Hi,

Im still getting the error of not having updates to 2.0 sdk.
Im using the bindings as you said, but i cannot find the ".a" files...

If i try using the framework, its 100mb extra.

What can i do?
Thanks!

**Comment by BlueRiverInteractive** [comment]
You just need to link to the framework in your robovm.xml (be sure to NOT add it to resources). The framework takes lots of disk space but when compiled it's just a few KB extra to your app.

**Comment by mcolombo** [comment]
Thank you so much!
Worked perfectly.
